package(default_visibility = ["//visibility:public"])

filegroup(
    name = "shader",
    srcs = glob([
        "*.frag",
        "*.vert",
    ]),
)

filegroup(
    name = "shader_spv",
    srcs = glob([
        "*.spv",
    ]),
)