cc_library(
    name = "texture_loader",
    srcs = ["texture_loader.cc"],
    hdrs = ["texture_loader.h"],
    deps = [
        "//zen/core/graphic_api",
        "//zen/core/renderer:texture",
        "@stb//:stb_image",
    ],
)
